// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt2aZ7liih0XNUwyKlZqv6FBZdiUC-t1s',
    appId: '1:829533365188:web:81e1fbb359bc60db077a91',
    messagingSenderId: '829533365188',
    projectId: 'livingmenu-bb117',
    authDomain: 'livingmenu-bb117.firebaseapp.com',
    storageBucket: 'livingmenu-bb117.firebasestorage.app',
    measurementId: 'G-YQ9VG4MET7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurOYw3QmbRayowQmh9oUbQ12zBtqIGNI',
    appId: '1:829533365188:android:e882563d54082183077a91',
    messagingSenderId: '829533365188',
    projectId: 'livingmenu-bb117',
    storageBucket: 'livingmenu-bb117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz4XZ6IMzOpCfbwscNhs5Oba2wgwxPVhc',
    appId: '1:829533365188:ios:c3e6fde24d47c132077a91',
    messagingSenderId: '829533365188',
    projectId: 'livingmenu-bb117',
    storageBucket: 'livingmenu-bb117.firebasestorage.app',
    iosBundleId: 'com.livingspark.livingMenuMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz4XZ6IMzOpCfbwscNhs5Oba2wgwxPVhc',
    appId: '1:829533365188:ios:c3e6fde24d47c132077a91',
    messagingSenderId: '829533365188',
    projectId: 'livingmenu-bb117',
    storageBucket: 'livingmenu-bb117.firebasestorage.app',
    iosBundleId: 'com.livingspark.livingMenuMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqif3X7ELe-AdhlVMkBFBye62vCdTrLBA',
    appId: '1:829533365188:web:1d293c063ac01e20077a91',
    messagingSenderId: '829533365188',
    projectId: 'livingmenu-bb117',
    authDomain: 'livingmenu-bb117.firebaseapp.com',
    storageBucket: 'livingmenu-bb117.firebasestorage.app',
    measurementId: 'G-QH7LS7BDB0',
  );
}
